report.pdf: report.tex
#	latex report.tex
#	bibtex report
#	latex report.tex
#	latex report.tex
#	dvipdf report.dvi
	

	pdflatex report.tex
	evince report.pdf
clean:
	@echo Cleaning...
	@rm *.aux *.log *.bbl *.blg  report.pdf report.dvi 

